### PR TITLE
add Chrome support

### PR DESCRIPTION
**Pull request by mrooney**
Hi there! This is super awesome and the live video with delay is just what I was looking for. I added Chrome support and tested that it still works in Firefox (45).

### CODE REVIEW

**Comment by april** [comment]
Thanks for this!  Sorry for taking so long to get back to you, just had my second kid.  :)

**Comment by mrooney** [comment]
Thanks and congrats! :D

**Comment by april** [comment]
I appreciate that.  BTW, I'm working on a rewrite of this that should fix that flicker problem.  It's pretty sweet, and I'll let you know when it's finished.  :)

**Comment by april** [comment]
Hey, could you take a look at: https://marumari.github.io/alexcam/

Let me know if the flickering issue is fixed for you?  I think I finally nailed it, with some fancy z-index trickery.

Also, if you can figure out how to get full screen working in Chrome, that would be awesome.  :)

Thanks!

**Comment by april** [comment]
Also, can I ask how you stumbled across this?  It's kind of hidden away!

**Comment by mrooney** [comment]
Awesome, the flicker is gone on Chrome, impressive job! :) Also, the PR that you merged includes fullscreen support from Chrome so that should already be working. I believe I found it by searching for something like "html5 webcam delay" or "live webcam delay". I'll have to merge that branch in with my use of it, are there any other changes you plan or is it good to go? And, thanks so much for this cool repository, I'm using it for handstand and partner acrobatic training so we can do something and then look over and see how it actually looks, very useful!

**Pull request merged**
